# Generated by Django 6.0 on 2026-01-19 03:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(max_length=100)),
                ("suffix", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "maiden_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Invalid PH mobile number",
                                regex="^(09|\\+639)\\d{9}$",
                            )
                        ],
                    ),
                ),
                ("current_address", models.CharField(max_length=255)),
                ("province", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("barangay", models.CharField(max_length=100)),
                ("zip_code", models.CharField(blank=True, max_length=4, null=True)),
                ("degree_program", models.CharField(max_length=200)),
                ("campus", models.CharField(default="UP Cebu", max_length=200)),
                (
                    "year_graduated",
                    models.CharField(
                        blank=True,
                        max_length=4,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Year must be 4 digits", regex="^\\d{4}$"
                            )
                        ],
                    ),
                ),
                (
                    "student_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "current_employer",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("job_title", models.CharField(blank=True, max_length=100, null=True)),
                ("industry", models.CharField(blank=True, max_length=100, null=True)),
                ("years_of_experience", models.IntegerField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("gcash", "GCash"),
                            ("bank", "Bank Transfer"),
                            ("cash", "Cash"),
                        ],
                        default="gcash",
                        max_length=20,
                    ),
                ),
                (
                    "gcash_reference_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "gcash_proof_of_payment",
                    models.FileField(blank=True, null=True, upload_to="payment/gcash/"),
                ),
                (
                    "bank_sender_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "bank_account_number",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "bank_reference_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "bank_proof_of_payment",
                    models.FileField(blank=True, null=True, upload_to="payment/bank/"),
                ),
                ("cash_payment_date", models.DateField(blank=True, null=True)),
                (
                    "cash_received_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("payment_notes", models.TextField(blank=True, null=True)),
                ("join_mentorship_program", models.BooleanField(default=False)),
                (
                    "mentorship_areas",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("mentorship_areas_other", models.TextField(blank=True, null=True)),
                (
                    "mentorship_industry_tracks",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "mentorship_industry_tracks_other",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "mentorship_format",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("one-on-one", "1-on-1 Mentorship"),
                            ("group", "Group Mentorship"),
                            ("both", "Either format works"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "mentorship_availability",
                    models.IntegerField(
                        blank=True, help_text="Hours per month", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "pending_alumni_verification",
                                "Pending Alumni Verification",
                            ),
                            (
                                "pending_payment_verification",
                                "Pending Payment Verification",
                            ),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("revoked", "Revoked"),
                        ],
                        db_index=True,
                        default="pending_alumni_verification",
                        max_length=30,
                    ),
                ),
                (
                    "date_applied",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("alumni_verified_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("alumni_verification", "Alumni Verification"),
                            ("payment_verification", "Payment Verification"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "alumni_verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alumni_verified_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "membership_applications",
                "ordering": ["-date_applied"],
            },
        ),
        migrations.CreateModel(
            name="VerificationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submitted", "Application Submitted"),
                            ("alumni_verified", "Alumni Verified"),
                            ("payment_confirmed", "Payment Confirmed"),
                            ("rejected", "Application Rejected"),
                            ("membership_revoked", "Membership Revoked"),
                            ("membership_reinstated", "Membership Reinstated"),
                        ],
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_history",
                        to="applications.membershipapplication",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Verification histories",
                "db_table": "verification_history",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="membershipapplication",
            index=models.Index(
                fields=["status", "date_applied"], name="membership__status_9c5564_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membershipapplication",
            index=models.Index(fields=["email"], name="membership__email_ff513a_idx"),
        ),
    ]
