# Generated by Django 6.0 on 2026-01-19 04:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipapplication',
            name='year_graduated',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator(message='Year must be 4 digits', regex='^\\d{4}$')]),
        ),
    ]
