# Generated by Django 6.0 on 2026-01-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipapplication',
            name='barangay',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='city',
            name='province',
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='province',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Barangay',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
