# Generated by Django 6.0 on 2026-01-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_make_year_graduated_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipapplication',
            name='campus',
            field=models.CharField(default='UP Cebu', max_length=200),
        ),
    ]
