# Generated by Django 6.0 on 2026-01-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_address_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipapplication',
            name='status',
            field=models.CharField(choices=[('pending_alumni_verification', 'Pending Alumni Verification'), ('pending_payment_verification', 'Pending Payment Verification'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], db_index=True, default='pending_alumni_verification', max_length=30),
        ),
        migrations.AlterField(
            model_name='verificationhistory',
            name='action',
            field=models.CharField(choices=[('submitted', 'Application Submitted'), ('alumni_verified', 'Alumni Verified'), ('payment_confirmed', 'Payment Confirmed'), ('rejected', 'Application Rejected'), ('membership_revoked', 'Membership Revoked'), ('membership_reinstated', 'Membership Reinstated')], max_length=30),
        ),
    ]
