# Generated by Django 6.0 on 2026-01-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_make_campus_required_with_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='id_photo',
            field=models.FileField(blank=True, null=True, upload_to='applications/id_photos/'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='tor_attachment',
            field=models.FileField(blank=True, help_text='Transcript of Records - Required if year_graduated is not provided', null=True, upload_to='applications/tor/'),
        ),
    ]
