# Generated by Django 6.0 on 2026-01-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_membershipapplication_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='bank_proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='payment_proofs/bank/'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='bank_reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='bank_sender_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='cash_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='cash_received_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='data_privacy_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='gcash_proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='payment_proofs/gcash/'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='gcash_reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='join_mentorship_program',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='mentorship_areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='mentorship_areas_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='mentorship_availability',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='mentorship_format',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='mentorship_industry_tracks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='mentorship_industry_tracks_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='years_of_experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
