# Generated by Django 6.0 on 2026-01-19 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_membershipapplication_bank_account_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipapplication',
            name='degree_program',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='membershipapplication',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='membershipapplication',
            name='data_privacy_consent',
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='campus',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='payment_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='zip_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='alumni_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumni_verified_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='bank_sender_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='cash_received_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='gcash_reference_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='mentorship_areas',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='mentorship_areas_other',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='mentorship_availability',
            field=models.IntegerField(blank=True, help_text='Hours per month', null=True),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='mentorship_format',
            field=models.CharField(blank=True, choices=[('one-on-one', '1-on-1 Mentorship'), ('group', 'Group Mentorship'), ('both', 'Either format works')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='mentorship_industry_tracks',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='mentorship_industry_tracks_other',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='payment_method',
            field=models.CharField(choices=[('gcash', 'GCash'), ('bank', 'Bank Transfer'), ('cash', 'Cash')], default='gcash', max_length=20),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verificationhistory',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_history', to='applications.membershipapplication'),
        ),
        migrations.DeleteModel(
            name='DegreeProgram',
        ),
    ]
