# Generated by Django 6.0 on 2026-01-19 14:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSettings',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('membership_fee', models.DecimalField(decimal_places=2, default=1450.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('gcash_accounts', models.JSONField(blank=True, default=list, help_text='List of GCash accounts: [{"name": "...", "number": "09XXXXXXXXX"}]')),
                ('bank_accounts', models.JSONField(blank=True, default=list, help_text='List of bank accounts: [{"bankName": "...", "accountName": "...", "accountNumber": "..."}]')),
                ('cash_payment', models.JSONField(blank=True, default=dict, help_text='Cash payment details: {"address": "", "building": "", "office": "", "openDays": [], "openHours": ""}')),
                ('success_message', models.CharField(blank=True, default='', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Form Settings',
                'verbose_name_plural': 'Form Settings',
                'db_table': 'form_settings',
            },
        ),
        migrations.CreateModel(
            name='FormSettingsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField(help_text='JSON object containing the changes made')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_settings_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Form Settings History',
                'verbose_name_plural': 'Form Settings History',
                'db_table': 'form_settings_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
