# Generated by Django 6.0 on 2026-01-09 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('verify_alumni', 'Verified Alumni'), ('reject_alumni', 'Rejected Alumni Verification'), ('approve_member', 'Approved Member'), ('reject_payment', 'Rejected Payment Verification'), ('revoke_member', 'Revoked Membership'), ('reinstate_member', 'Reinstated Membership'), ('deactivate_admin', 'Deactivated Admin'), ('reactivate_admin', 'Reactivated Admin')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('target_type', models.CharField(blank=True, choices=[('application', 'Application'), ('member', 'Member'), ('admin', 'Admin User')], max_length=20, null=True)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('target_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_activity_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['admin', '-timestamp'], name='admin_activ_admin_i_336b22_idx'), models.Index(fields=['action', '-timestamp'], name='admin_activ_action_21303d_idx')],
            },
        ),
    ]
