# Generated by Django 6.0 on 2026-01-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactivitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('verify_alumni', 'Verified Alumni'), ('reject_alumni', 'Rejected Alumni Verification'), ('approve_member', 'Approved Member'), ('reject_payment', 'Rejected Payment Verification'), ('revoke_member', 'Revoked Membership'), ('reinstate_member', 'Reinstated Membership'), ('deactivate_admin', 'Deactivated Admin'), ('reactivate_admin', 'Reactivated Admin'), ('form_settings_updated', 'Updated Form Settings')], max_length=30),
        ),
        migrations.AlterField(
            model_name='adminactivitylog',
            name='target_type',
            field=models.CharField(blank=True, choices=[('application', 'Application'), ('member', 'Member'), ('admin', 'Admin User'), ('form_settings', 'Form Settings')], max_length=20, null=True),
        ),
    ]
