# Generated by Django 6.0 on 2026-01-02 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_since', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to='applications.membershipapplication')),
            ],
            options={
                'db_table': 'members',
                'ordering': ['-member_since'],
            },
        ),
    ]
